# Generated by Django 5.2 on 2025-05-02 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS_Marketplace', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='PMS_Marketplace.category'),
        ),
    ]
