INSERT INTO pharma_Product (name, description, image, category)
VALUES 
("Bubblez Shea Butter Avocado Oil Leave-in Cream 350ml", "A nourishing leave-in cream infused with shea butter and avocado oil, ideal for all hair types.", "products/bubblez-shea-butter-avocado-oil-leave-in-cream-for-all-hair-types-350ml-728613.webp", "Hair Care"),
("Cerave Eye Repair Cream 14ml", "A dermatologist-developed eye repair cream that helps reduce dark circles and puffiness.", "products/cerave-eye-repair-cream-14ml-137958.webp", "Skin Care"),
("Cerave Facial Lotion PM 52ml", "A lightweight nighttime facial lotion with ceramides and niacinamide for deep hydration.", "products/cerave-facial-lotion-pm-52ml-483297.webp", "Skin Care"),
("Clinique Dramatically Different Moisturizing Gel 125ml", "A non-greasy, lightweight gel moisturizer that provides hydration for oily and combination skin.", "products/clinique-dramatically-different-moisturizing-gel-with-pump-125ml-409463.webp", "Skin Care"),
("Cosrx Advanced Snail 96 Mucin Power Essence 100ml", "A repairing essence enriched with 96% snail mucin to hydrate, heal, and brighten skin.", "products/cosrx-advanced-snail-96-mucin-power-essence-serum-100ml-114502.webp", "Skin Care"),
("Essentials Candy Infused Lip Scrub 20ml", "A gentle exfoliating lip scrub infused with candy extracts for smooth, soft lips.", "products/essentials-candy-infused-lip-scrub-20ml-931105.webp", "Lip Care"),
("Garnier Micellar Cleansing Water 100ml", "A micellar cleansing water designed to remove makeup and impurities gently.", "products/garnier-micellar-cleansing-water-for-sensitive-skin-100ml-261017.webp", "Skin Care"),
("Gillette Blue II Plus Disposable Razors (5 Pack)", "A pack of five disposable razors designed for a smooth and comfortable shave.", "products/gillette-blue-ii-plus-for-women-5-disposable-razors-973210.webp", "Personal Care"),
("Joviiality Strong & Long Nourishing Nail Cuticle Oil", "A nourishing nail cuticle oil that promotes healthy nail growth.", "products/joviiality-strong-n-long-nourishing-nail-cuticle-oil-542674.webp", "Nail Care"),
("La Roche-Posay Cicaplast Baume B5 40ml", "A multi-purpose soothing balm for sensitive and irritated skin, enriched with vitamin B5.", "products/la-roche-posay-cicaplast-baume-b5-soothing-repairing-balm-40ml-440495.webp", "Skin Care"),
("La Roche-Posay Hyalu B5 Serum 30ml", "A hydrating anti-aging serum with hyaluronic acid and vitamin B5.", "products/la-roche-posay-hyalu-b5-serum-30ml-338408.webp", "Skin Care"),
("La Roche-Posay Mela B3 Cleanser 200ml", "A gentle facial cleanser that brightens skin and reduces dark spots.", "products/la-roche-posay-mela-b3-cleanser-200ml-817970.webp", "Skin Care"),
("L'Oreal Absolut Repair Quinoa Protein Shampoo 300ml", "A professional-grade shampoo that repairs damaged hair with quinoa protein.", "products/loreal-professional-absolut-repair-quinoa-protein-shampoo-300ml-222167.webp", "Hair Care"),
("Mood Bali Shower Gel 750ml", "An exotic shower gel with tropical fragrances for a refreshing bath experience.", "products/mood-bali-shower-gel-750ml-780103.webp", "Body Care"),
("Neutrogena Hydro Boost Water Gel 50ml", "A hydrating water gel moisturizer enriched with hyaluronic acid.", "products/neutrogena-hydro-boost-water-gel-50ml-443968.webp", "Skin Care"),
("Neutrogena Hydro Boost Face Cleanser 200ml", "A lightweight gel cleanser that removes dirt and oil while maintaining hydration.", "products/neutrogena-hydro-boost-water-gel-face-cleanser-200ml-607755.webp", "Skin Care"),
("Olaplex Hair Perfector No.3 100ml", "A deep conditioning treatment that strengthens and repairs damaged hair.", "products/olaplex-hair-perfector-no3-100ml-902281.webp", "Hair Care"),
("Raw African Follicle Booster Oil 100ml", "A natural hair oil that stimulates hair growth and strengthens follicles.", "products/raw-african-follicle-booster-oil-100ml-107474.webp", "Hair Care"),
("The Ordinary Hyaluronic Acid 2% + B5 30ml", "A hydrating serum with hyaluronic acid and vitamin B5 for plump, smooth skin.", "products/the-ordinary-hyaluronic-acid-2-b5-solution-30ml-316654.webp", "Skin Care"),
("The Ordinary Niacinamide 10% + Zinc 1%", "A powerful serum that reduces blemishes and balances oil production.", "products/the-ordinary-niacinamide-10-zinc-1-solution-egcg-30ml-296129.webp", "Skin Care"),
("Vaseline Cocoa Radiant Vitalizing Body Gel Oil 200ml", "A hydrating body oil infused with cocoa butter for deep nourishment.", "products/vaseline-cocoa-radiant-vitalizing-body-gel-oil-200ml-315328.webp", "Body Care"),
("Vaseline Lip Therapy Rosy Tinted Balm 10gm", "A tinted lip balm that provides hydration with a rosy glow.", "products/vaseline-lip-therapy-rosy-tinted-lip-balm-10gm-632415.webp", "Lip Care");
